// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAelUva8ArxU3rhPo9ZCGcQsv61aZpPfHQ',
    appId: '1:477199306502:web:69499ab60d1740cc105887',
    messagingSenderId: '477199306502',
    projectId: 'capefluttermvvm',
    authDomain: 'capefluttermvvm.firebaseapp.com',
    storageBucket: 'capefluttermvvm.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJJB-AFpeH2F_JOphx9-NURBYjmx4xq8U',
    appId: '1:477199306502:android:3c8828c5f67f44b2105887',
    messagingSenderId: '477199306502',
    projectId: 'capefluttermvvm',
    storageBucket: 'capefluttermvvm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK2bJ_qDbDZGXblQMH-9tqdE6Kkxav70w',
    appId: '1:477199306502:ios:4d4b4699622bd53d105887',
    messagingSenderId: '477199306502',
    projectId: 'capefluttermvvm',
    storageBucket: 'capefluttermvvm.appspot.com',
    iosClientId: '477199306502-cl2kom4rji98seg3l4cm5gu5b0gqucvs.apps.googleusercontent.com',
    iosBundleId: 'com.change.package.mvvmbasic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK2bJ_qDbDZGXblQMH-9tqdE6Kkxav70w',
    appId: '1:477199306502:ios:4ba0e6d1b9bf0dd0105887',
    messagingSenderId: '477199306502',
    projectId: 'capefluttermvvm',
    storageBucket: 'capefluttermvvm.appspot.com',
    iosClientId: '477199306502-k41guofkg45de514bgmr5nq1o2it44hl.apps.googleusercontent.com',
    iosBundleId: 'com.change.package.mvvmbasic.RunnerTests',
  );

}
